name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite UTC

  workflow_dispatch:  # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: kimberlisabino
          outputs: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update Snake animation" || echo "No changes to commit"
          git push
